<?php

echo $this->doctype();

?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(''. $this->translate('Minute Board'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/minuteboard.min.js')
            ->prependFile($this->basePath() . '/js/vendorpackage.min.js')
            ->prependFile($this->basePath() . '/js/vendor/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/vendor/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))

        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Minute Board') ?></a>
                    <p class="navbar-text navbar-right">
                        <strong>Remaining: <span id="timeremaining">7:43</span></strong>
                    </p>
                </div>
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="<?php echo $controller == 'index' ? 'active' : ''?>"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('About') ?></a></li>
                        <li class="<?php echo $controller == 'blog' ? 'active' : ''?>"><a href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('Current') ?></a></li>
                        <li class="<?php echo $controller == 'archive' ? 'active' : ''?>"><a href="<?php echo $this->url('archive') ?>"><?php echo $this->translate('Archive') ?></a></li>
                        <li class="<?php echo $controller == 'topic' ? 'active' : ''?>"><a href="<?php echo $this->url('topic') ?>"><?php echo $this->translate('Topics') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->

            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by Michael Reiniger. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
